### ISSUE TITLE
Roundcube wrong config path - Debian 9

### ISSUE THREAD

**Issue by spont4e** [servisys/ispconfig_setup#196]
You had to edit user/pass **/var/lib/roundcube/plugins/ispconfig3_account/config/config.inc.php** of roudcube user, as the one you inserted in ISPconfig

Missing folder ispconfig3_account. Where to put user/pass ?

**Comment by servisys** [comment]
Mmm probably, plugin not I stalled, the guy pushed the update missed this
point.

Maybe got to fix.

But should work, only problem you can't change the password from roundcube.

Inviato da Nexus 6

Il 09 lug 2017 2:35 PM, "spont4e" <notifications@github.com> ha scritto:

**Comment by spont4e** [comment]
In my case mail server doesn't work, but problem has in /etc/postfix/master.cf
Problem solved after i was removed comment from this line
`tlsproxy  unix  -       -       y       -       0       tlsproxy`

**Comment by calbasi** [comment]
Same issue here... 

ps: And, what's the roundcube password? Install script didn't ask me for a password. I've had to figure that ispconfig usr/password is admin/admin (opening a new issue just now)

**Comment by servisys** [comment]
Fixed tls, got to check for the other things

**Comment by Neustradamus** [comment]
I have launch the installer but I have:
You had to edit user/pass /var/lib/roundcube/plugins/ispconfig3_account/config/config.inc.php of roudcube user, as the one you inserted in ISPconfig

There is not /var/lib/roundcube/plugins/ispconfig3_account

A part is missing in script?

**Comment by Neustradamus** [comment]
It is resolved?

**Comment by kovalroma** [comment]
@Neustradamus No, it is still exist. Just installed ISPConfig on Ubuntu 18 and got the same message.

**Comment by promotion** [comment]
Confirm - same message :
"You will need to edit the username and password in /var/lib/roundcube/plugins/ispconfig3_account/config/config.inc.php of the roundcube user, as the one you set in ISPconfig " 

However - no such plugin in that folder

**Comment by haliluluoglu** [comment]
Is there any update about this issue?(No such file or directory)
